name: Build
run-name: ${{github.actor}} - ${{github.workflow}}
on:
  push:
    branches:
      - "**"

env:
  EXECUTABLE: "qtsandbox"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qt6-base-dev libgl1-mesa-dev

      - name: Build
        run: ./build.sh build

      - name: Check binary
        run: |
          if [[ ! -x "./${EXECUTABLE}" ]]; then
          echo "Error: Binary ${EXECUTABLE} not found."
          exit 1
          fi
